name: to_do_list
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get_storage: ^2.0.3
  get: ^4.6.5
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  google_fonts: ^3.0.1
  sqflite: ^2.2.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.6
  rxdart: ^0.27.7

  date_picker_timeline: ^1.2.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
